### ISSUE TITLE
Not able to load data.

### ISSUE THREAD

**Issue by parthanjaria** [Mayank-AMR/News#1]
Tried to install the app. Getting this error : {"status":"error","code":"apiKeyInvalid","message":"Your API key is invalid or incorrect. Check your key, or go to https://newsapi.org to create a free API key."}
what is the reason behind it?

@Mayank-AMR

**Comment by Mayank-AMR** [comment]
Because of Github public repository, I had removed the API key from
project. To run this project you need API-Key. I have already
mentioned this in README.md file of this project.

You can use my Private API key to run this project:-
 "7be9224ddeaa419e9d9cbffd5de2cf49"

Paste the API-Key as a variable named API_KEY in the file
"ArticleMediator.kt" located at
"com.mayank_amr.news.data.repository.paging" package.

You can also visit  https://github.com/Mayank-AMR/News#readme

Thankyou.

**Comment by Mayank-AMR** [comment]
I have removed API-Key for security reasons as experts recommend this.

Hope you will now able to run this project successfully. If you face
any issue please write me back.

I also request you to please give me feedback that will help me a lot
 to understand my coding skill.

Thankyou.
8707448655

**Comment by Mayank-AMR** [comment]
Actually this is not an error. To run this app, you must have an **[API Key](https://newsapi.org/)** from [newsapi.org/](https://newsapi.org/) at position defined as a variable named **API_KEY** in the file **[ArticleMediator.kt](https://github.com/Mayank-AMR/News/blob/main/app/src/main/java/com/mayank_amr/news/data/repository/paging/ArticleMediator.kt)** located at **com.mayank_amr.news.data.repository.paging** package.

For security reason I can't upload API Key as publicly.

Hope you will now able to run this project successfully. If you face
any issue please write me back.
